EX1/Models/ErrorViewModel.cs
using System;

namespace WebMVC_Manha.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EX1/Models/Musica.cs
namespace WebMVC_Manha.Models
{
    public class Musica
    {
        public string Titulo {get;set;}
        public string Estilo {get;set;}
        public string Compositor {get;set;}

        public Musica ()
        {

        }

        public Musica (string titulo, string estilo, string compositor)
        {
            this.Titulo = titulo;
            this.Estilo = estilo;
            this.Compositor = compositor;
        }
    }
}

EX1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebMVC_Manha.Models;

namespace WebMVC_Manha.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EX1/Controllers/MusicaController.cs
using Microsoft.AspNetCore.Mvc;
using WebMVC_Manha.Models;
using WebMVC_Manha.Repositorios;

namespace WebMVC_Manha.Controllers
{
    public class MusicaController : Controller
    {
        public IActionResult Index() 
        {
            return View();
        }

        public IActionResult Welcome(string nome)
        {
            
            
            ViewData["Mensagem"] = "Olá " + nome + ", estas são as suas músicas";
            var musica = MusicaRepositorio.musicas[0];
            

            return View(musica);
        }
    }
}

EX1/Views/Musica/Index.cshtml
@{
    ViewData["Title"] = "Lista de Músicas";
}

<h2>@ViewData["Title"]</h2>

<p>Nossa lista de músicas</p>

EX1/Views/Musica/Welcome.cshtml
@model WebMVC_Manha.Models.Musica
@{
    ViewData["Title"] = "Bem-vindo (a)!";
}

<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Mensagem"]</h3>

<p><strong>Titulo</strong></p>
<p>@Model.Titulo</p>
<p><strong>Estilo</strong></p>
<p>@Model.Estilo</p>
<p><strong>Compositor</strong></p>
<p>@Model.Compositor</p>

EX1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Music App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebMVC_Manha</a> -->
                <a asp-area="" asp-controller="Musica" asp-action="Index" class="navbar-brand">Music App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebMVC_Manha</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>